# Generated by Django 4.0.3 on 2022-04-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField()),
                ('stock', models.CharField(max_length=255)),
                ('start_volume', models.FloatField(verbose_name='Начальный объем')),
                ('end_volume', models.FloatField(verbose_name='Конечный объем')),
                ('fee', models.FloatField()),
                ('profit', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('api_key', models.CharField(max_length=255)),
                ('fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('deals', models.IntegerField()),
                ('profit', models.FloatField()),
                ('fees', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Summaries',
            },
        ),
    ]
